# ----
# Site

title: Aviator
description: Jekyll template for API documentation.
url: https://example.com
google_analytics_key:
permalink: pretty
# -----
# Build


collections:
  documentation:
    title: Documentation
    position: 1
  employee:
    title: Employee
    position: 2
  suppliers:
    title: Supplier
    position: 3
  customers:
    title: Customers
    position: 4
  item:
    title: Item
    position: 5
  stock:
    title: Stock
    position: 6
  manufacture:
    title: Manufacture
    position: 7
  purchase:
    title: Purchase
    position: 8
  sales:
    title: Sales
    position: 9
  approvals:
    title: Approvals
    position: 10
  job:
    title: Job
    position: 11
  finace:
    title: Finance
    position: 12
  appoinments:
    title:  Appoinments
    position: 13
  report:
    title: Report
    position: 14
    
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENSE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      type: "documentation"
    values:
      _hide_content: true
  -
    scope:
      type: "api"
    values:
      _hide_content: true

# -----------
# CloudCannon

types:
  - get
  - put
  - delete
  - post

languages:
  bash: Bash
  c: C
  css: CSS
  html: HTML
  java: Java
  javascript: JavaScript
  json: JSON
  php: PHP
  python: Python
  ruby: Ruby

_options:
  content_markdown:
    format: p h4 h5 h6
    bold: true
    italic: true
    link: true
    bulletedlist: true
    numberedlist: true
    image: true
    table: true
    styles: /css/editor.css
